version: '3'
services:
  my_mysql:
    image: mysql:latest
    volumes:
      - "/Users/llasry/Documents/www/mysql_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

#  my_node:
#    image: node:onbuild
#    volumes:
#      - ".:/usr/src/app"
#      - "node_volume:/usr/local/lib/node_modules/npm"
#    ports:
#      - "3000:3000"
#    working_dir: "/usr/share/nginx/html"

#Warning php and nginx document root should be the same (here usr/share/nginx/html)

#  my_casper:
#    image: zopanix/casperjs
#    volumes:
#      - ".:/data"
#      - "/usr/local/bin"
#      - "/opt/casperjs/bin"
#    working_dir: "/usr/local/bin"

  my_php7:
    build: ./build/webstack
    depends_on:
      - my_mysql
    image: webstack
#    volumes_from:
#      - my_casper
    volumes:
      - "../:/usr/share/nginx/html:rw"
      - "./php7/php.ini:/usr/local/etc/php/php.ini:ro"
#      - "my_casper_volume:/usr/local/bin/casperjs"
#      - "node_volume:/usr/local/lib/node_modules/npm"
#    links:
#      - my_mysql
#      - my_mycasper
    ports:
      - "9000:9000"
      - "3000:3000"
      - "4000:4000"
    restart: always
    working_dir: "/usr/share/nginx/html"

  my_nginx:
    depends_on:
      - my_php7
    image: nginx:latest
    volumes:
      - "../:/usr/share/nginx/html:rw"
      - "./nginx/var/log:/var/log/nginx:rw"
      - "./nginx/nginx.template.conf:/etc/nginx/conf.d/nginx.template:rw"
      - "./nginx/sites-available:/etc/nginx/sites-available:rw"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled:rw"
    links:
      - my_php7:webstack_php
    environment:
      - KEEPALIVE_TIMEOUT=${KEEPALIVE_TIMEOUT}
    ports:
      - "8080:8080"
      - "8090:90"
      - "8091:91"
      - "8083:8083"
      - "80:80"
    restart: always
    command: /bin/bash -c "cp /etc/nginx/conf.d/nginx.template /etc/nginx/conf.d/nginx.conf && nginx -c /etc/nginx/conf.d/nginx.conf"
